# app/modules/Make_product_model/models.py
import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, Integer, String, DateTime, func, Index
from app.core.database import Base
from sqlalchemy.dialects.postgresql import UUID


class MakeProductModel(Base):
    __tablename__ = "make_product_models"

    # Custom unique identifier generated by the application
    id = Column(UUID(as_uuid=True), unique=True, primary_key=True, default=uuid.uuid4)

    # Core Identifiers from JSON
    product_id = Column(Integer, unique=True, nullable=False, index=True)
    model_id = Column(Integer, nullable=True, index=True)
    category_id = Column(Integer, nullable=True, index=True)
    sub_category_id = Column(Integer, nullable=True, index=True)

    # Descriptive Details from JSON
    make = Column(String(255), nullable=False, index=True)
    model = Column(String(500), nullable=False)
    decal_model = Column(String(500), nullable=True)
    category = Column(String(255), nullable=False, index=True)
    sub_category = Column(String(255), nullable=True, index=True)
    division = Column(String(100), nullable=True)
    jd_product_family = Column(String(255), nullable=True)

    # Audit Timestamps
    created_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        nullable=False,
    )
    updated_at = Column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        server_default=func.now(),
        onupdate=lambda: datetime.now(timezone.utc),
        nullable=False,
    )

    # Performance Indexes
    __table_args__ = (
        Index("ix_make_product_model_make_model", "make", "model"),
        Index("ix_make_product_model_make_category", "make", "category"),
        Index("ix_make_product_model_make_sub_category", "make", "sub_category"),
        Index("ix_make_product_model_make_division", "make", "division"),
        Index(
            "ix_make_product_model_make_jd_product_family", "make", "jd_product_family"
        ),
        Index("ix_make_product_model_model_id", "model_id"),
        Index("ix_make_product_model_category_id", "category_id"),
        Index("ix_make_product_model_sub_category_id", "sub_category_id"),
        Index("ix_make_product_model_product_id", "product_id"),
        Index("ix_make_product_model_created_at", "created_at"),
        Index("ix_make_product_model_updated_at", "updated_at"),
        Index("ix_make_product_model_make", "make"),
        Index("ix_make_product_model_model", "model"),
        Index("ix_make_product_model_category", "category"),
        Index("ix_make_product_model_sub_category", "sub_category"),
        Index("ix_make_product_model_division", "division"),
        Index("ix_make_product_model_jd_product_family", "jd_product_family"),
    )
