"""Add is_active to users table

Revision ID: 6bc76e4898d9
Revises: b0a9518cf3bc
Create Date: 2026-09-19 22:37:10.014749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bc76e4898d9'
down_revision: Union[str, Sequence[str], None] = 'b0a9518cf3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_make_product_model_category'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_model_category_id'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_model_created_at'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_model_division'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_model_jd_product_family'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_model_make'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_model_make_category'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_model_make_division'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_model_make_jd_product_family'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_model_make_model'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_model_make_sub_category'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_model_model'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_model_model_id'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_model_product_id'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_model_sub_category'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_model_sub_category_id'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_model_updated_at'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_category'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_category_id'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_make'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_model_id'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_product_id'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_sub_category'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_sub_category_id'), table_name='make_product_models')
    op.drop_table('make_product_models')
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_assets_customer_id'), table_name='assets')
    op.add_column('branches', sa.Column('division_name', sa.String(length=255), nullable=False))
    op.drop_index(op.f('ix_branches_lob_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_name'), table_name='branches')
    op.create_index('ix_branches_name', 'branches', ['name'], unique=False)
    op.drop_constraint(op.f('branches_lob_id_fkey'), 'branches', type_='foreignkey')
    op.create_foreign_key(None, 'branches', 'line_of_businesses', ['lob_id'], ['id'])
    op.add_column('customers', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('address', sa.String(length=500), nullable=True))
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.alter_column('line_of_businesses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('line_of_businesses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_line_of_businesses_division_name'), table_name='line_of_businesses')
    op.drop_index(op.f('ix_line_of_businesses_lob_name'), table_name='line_of_businesses')
    op.create_unique_constraint(None, 'line_of_businesses', ['lob_name'])
    op.alter_column('sales_type_lookup', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sales_type_lookup', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('work_order_status_lookup', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('work_order_status_lookup', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('work_order_tasks_work_order_id_fkey'), 'work_order_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'work_order_tasks', 'work_orders', ['work_order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('work_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('work_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_work_orders_asset_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_customer_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_status_id'), table_name='work_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_work_orders_status_id'), 'work_orders', ['status_id'], unique=False)
    op.create_index(op.f('ix_work_orders_customer_id'), 'work_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_work_orders_asset_id'), 'work_orders', ['asset_id'], unique=False)
    op.alter_column('work_orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('work_orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'work_order_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('work_order_tasks_work_order_id_fkey'), 'work_order_tasks', 'work_orders', ['work_order_id'], ['id'])
    op.alter_column('work_order_status_lookup', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('work_order_status_lookup', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'is_active')
    op.alter_column('sales_type_lookup', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sales_type_lookup', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'line_of_businesses', type_='unique')
    op.create_index(op.f('ix_line_of_businesses_lob_name'), 'line_of_businesses', ['lob_name'], unique=False)
    op.create_index(op.f('ix_line_of_businesses_division_name'), 'line_of_businesses', ['division_name'], unique=False)
    op.alter_column('line_of_businesses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('line_of_businesses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('customers', 'address')
    op.drop_column('customers', 'phone')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.create_foreign_key(op.f('branches_lob_id_fkey'), 'branches', 'line_of_businesses', ['lob_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('ix_branches_name', table_name='branches')
    op.create_index(op.f('ix_branches_name'), 'branches', ['name'], unique=True)
    op.create_index(op.f('ix_branches_lob_id'), 'branches', ['lob_id'], unique=False)
    op.drop_column('branches', 'division_name')
    op.create_index(op.f('ix_assets_customer_id'), 'assets', ['customer_id'], unique=False)
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table('make_product_models',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sub_category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('make', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('decal_model', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('sub_category', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('division', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('jd_product_family', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('make_product_models_pkey'))
    )
    op.create_index(op.f('ix_make_product_models_sub_category_id'), 'make_product_models', ['sub_category_id'], unique=False)
    op.create_index(op.f('ix_make_product_models_sub_category'), 'make_product_models', ['sub_category'], unique=False)
    op.create_index(op.f('ix_make_product_models_product_id'), 'make_product_models', ['product_id'], unique=True)
    op.create_index(op.f('ix_make_product_models_model_id'), 'make_product_models', ['model_id'], unique=False)
    op.create_index(op.f('ix_make_product_models_make'), 'make_product_models', ['make'], unique=False)
    op.create_index(op.f('ix_make_product_models_category_id'), 'make_product_models', ['category_id'], unique=False)
    op.create_index(op.f('ix_make_product_models_category'), 'make_product_models', ['category'], unique=False)
    op.create_index(op.f('ix_make_product_model_updated_at'), 'make_product_models', ['updated_at'], unique=False)
    op.create_index(op.f('ix_make_product_model_sub_category_id'), 'make_product_models', ['sub_category_id'], unique=False)
    op.create_index(op.f('ix_make_product_model_sub_category'), 'make_product_models', ['sub_category'], unique=False)
    op.create_index(op.f('ix_make_product_model_product_id'), 'make_product_models', ['product_id'], unique=False)
    op.create_index(op.f('ix_make_product_model_model_id'), 'make_product_models', ['model_id'], unique=False)
    op.create_index(op.f('ix_make_product_model_model'), 'make_product_models', ['model'], unique=False)
    op.create_index(op.f('ix_make_product_model_make_sub_category'), 'make_product_models', ['make', 'sub_category'], unique=False)
    op.create_index(op.f('ix_make_product_model_make_model'), 'make_product_models', ['make', 'model'], unique=False)
    op.create_index(op.f('ix_make_product_model_make_jd_product_family'), 'make_product_models', ['make', 'jd_product_family'], unique=False)
    op.create_index(op.f('ix_make_product_model_make_division'), 'make_product_models', ['make', 'division'], unique=False)
    op.create_index(op.f('ix_make_product_model_make_category'), 'make_product_models', ['make', 'category'], unique=False)
    op.create_index(op.f('ix_make_product_model_make'), 'make_product_models', ['make'], unique=False)
    op.create_index(op.f('ix_make_product_model_jd_product_family'), 'make_product_models', ['jd_product_family'], unique=False)
    op.create_index(op.f('ix_make_product_model_division'), 'make_product_models', ['division'], unique=False)
    op.create_index(op.f('ix_make_product_model_created_at'), 'make_product_models', ['created_at'], unique=False)
    op.create_index(op.f('ix_make_product_model_category_id'), 'make_product_models', ['category_id'], unique=False)
    op.create_index(op.f('ix_make_product_model_category'), 'make_product_models', ['category'], unique=False)
    # ### end Alembic commands ###
