"""Add business table, update branch with business_id and branch_manager_id, add department table

Revision ID: 8f1d2c3b4a5e
Revises: 70b96a6c02a7
Create Date: 2026-09-20 22:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8f1d2c3b4a5e'
down_revision: Union[str, Sequence[str], None] = '70b96a6c02a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address1', sa.String(length=500), nullable=True),
    sa.Column('address2', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_email'), 'businesses', ['email'], unique=False)
    op.create_index(op.f('ix_businesses_name'), 'businesses', ['name'], unique=False)
    op.create_index(op.f('ix_businesses_is_active'), 'businesses', ['is_active'], unique=False)

    # Add business_id and branch_manager_id to branch table as nullable first
    op.add_column('branches', sa.Column('business_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('branches', sa.Column('branch_manager_id', postgresql.UUID(as_uuid=True), nullable=True))

    # Create a default business for existing branches
    # We'll insert a default business and get its ID
    # Using a fixed UUID for reproducibility in migrations
    default_business_id = '00000000-0000-0000-0000-000000000001'
    op.execute(
        sa.text(f"""
        INSERT INTO businesses (id, name, description, email, phone, address1, address2, city, state, country, postal_code, website_url, is_active, created_at, updated_at)
        VALUES ('{default_business_id}'::uuid, 'Default Business', 'Default business created during migration', NULL, NULL, NULL, NULL, 'Unknown', NULL, 'Unknown', NULL, NULL, TRUE, now(), now())
        """)
    )

    # Update existing branches to use the default business
    op.execute(
        sa.text(f"UPDATE branches SET business_id = '{default_business_id}' WHERE business_id IS NULL")
    )

    # Now make business_id NOT NULL
    op.alter_column('branches', 'business_id', nullable=False)

    # Create foreign keys
    op.create_foreign_key(None, 'branches', 'businesses', ['business_id'], ['id'])
    op.create_foreign_key(None, 'branches', 'users', ['branch_manager_id'], ['id'])
    op.create_index(op.f('ix_branches_business_id'), 'branches', ['business_id'], unique=False)
    op.create_index(op.f('ix_branches_branch_manager_id'), 'branches', ['branch_manager_id'], unique=False)

    # Create department table
    op.create_table('departments',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('branch_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('manager_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], )
    )
    op.create_index(op.f('ix_departments_branch_id'), 'departments', ['branch_id'], unique=False)
    op.create_index(op.f('ix_departments_manager_id'), 'departments', ['manager_id'], unique=False)
    op.create_index(op.f('ix_departments_is_active'), 'departments', ['is_active'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_is_active'), table_name='departments')
    op.drop_index(op.f('ix_departments_manager_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_branch_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_branches_branch_manager_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_business_id'), table_name='branches')
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_column('branches', 'branch_manager_id')
    op.drop_column('branches', 'business_id')
    op.drop_index(op.f('ix_businesses_is_active'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_name'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_email'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###