"""describe changes here

Revision ID: ab0b855f12fa
Revises: 
Create Date: 2026-09-21 22:44:49.226707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab0b855f12fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('number', sa.Integer(), sa.Identity(always=False, start=10001), nullable=False),
    sa.Column('address1', sa.String(length=500), nullable=True),
    sa.Column('address2', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('join_key', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('division_name', sa.String(length=255), nullable=True),
    sa.Column('lob_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index('ix_branches_business_div', 'branches', ['lob_name', 'division_name'], unique=False)
    op.create_index(op.f('ix_branches_city'), 'branches', ['city'], unique=False)
    op.create_index(op.f('ix_branches_country'), 'branches', ['country'], unique=False)
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.create_index(op.f('ix_branches_is_active'), 'branches', ['is_active'], unique=False)
    op.create_index(op.f('ix_branches_join_key'), 'branches', ['join_key'], unique=True)
    op.create_index('ix_branches_location_composite', 'branches', ['country', 'province', 'city'], unique=False)
    op.create_index(op.f('ix_branches_name'), 'branches', ['name'], unique=False)
    op.create_index(op.f('ix_branches_province'), 'branches', ['province'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branches_province'), table_name='branches')
    op.drop_index(op.f('ix_branches_name'), table_name='branches')
    op.drop_index('ix_branches_location_composite', table_name='branches')
    op.drop_index(op.f('ix_branches_join_key'), table_name='branches')
    op.drop_index(op.f('ix_branches_is_active'), table_name='branches')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_country'), table_name='branches')
    op.drop_index(op.f('ix_branches_city'), table_name='branches')
    op.drop_index('ix_branches_business_div', table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
