"""add make product model table and sync schemas

Revision ID: acd7358a40d2
Revises: 
Create Date: 2026-09-18 21:19:31.817587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acd7358a40d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_of_businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('division_name', sa.String(length=255), nullable=False),
    sa.Column('division_abbreviation', sa.String(length=50), nullable=True),
    sa.Column('lob_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_line_of_businesses_division_name', 'line_of_businesses', ['division_name'], unique=False)
    op.create_index('ix_line_of_businesses_lob_name', 'line_of_businesses', ['lob_name'], unique=False)
    op.create_table('make_product_models',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('sub_category', sa.String(length=255), nullable=True),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('jd_product_family', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_make_product_model_category_sub_category', 'make_product_models', ['category', 'sub_category'], unique=False)
    op.create_index('ix_make_product_model_division', 'make_product_models', ['division'], unique=False)
    op.create_index('ix_make_product_model_jd_product_family', 'make_product_models', ['jd_product_family'], unique=False)
    op.create_index('ix_make_product_model_make_category', 'make_product_models', ['make', 'category'], unique=False)
    op.create_index('ix_make_product_model_make_model', 'make_product_models', ['make', 'model'], unique=False)
    op.create_index('ix_make_product_model_model_id', 'make_product_models', ['model_id'], unique=False)
    op.create_index('ix_make_product_model_product_id', 'make_product_models', ['product_id'], unique=False)
    op.create_index(op.f('ix_make_product_models_category'), 'make_product_models', ['category'], unique=False)
    op.create_index(op.f('ix_make_product_models_make'), 'make_product_models', ['make'], unique=False)
    op.create_index(op.f('ix_make_product_models_model_id'), 'make_product_models', ['model_id'], unique=False)
    op.create_index(op.f('ix_make_product_models_product_id'), 'make_product_models', ['product_id'], unique=True)
    op.create_index(op.f('ix_make_product_models_sub_category'), 'make_product_models', ['sub_category'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lob_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('number', sa.Integer(), sa.Identity(always=False, start=10001), nullable=False),
    sa.Column('address1', sa.String(length=500), nullable=True),
    sa.Column('address2', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('province', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lob_id'], ['line_of_businesses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index('ix_branches_email', 'branches', ['email'], unique=False)
    op.create_index('ix_branches_is_active', 'branches', ['is_active'], unique=False)
    op.create_index(op.f('ix_branches_lob_id'), 'branches', ['lob_id'], unique=False)
    op.create_index('ix_branches_name', 'branches', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_branches_name', table_name='branches')
    op.drop_index(op.f('ix_branches_lob_id'), table_name='branches')
    op.drop_index('ix_branches_is_active', table_name='branches')
    op.drop_index('ix_branches_email', table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_make_product_models_sub_category'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_product_id'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_model_id'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_make'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_category'), table_name='make_product_models')
    op.drop_index('ix_make_product_model_product_id', table_name='make_product_models')
    op.drop_index('ix_make_product_model_model_id', table_name='make_product_models')
    op.drop_index('ix_make_product_model_make_model', table_name='make_product_models')
    op.drop_index('ix_make_product_model_make_category', table_name='make_product_models')
    op.drop_index('ix_make_product_model_jd_product_family', table_name='make_product_models')
    op.drop_index('ix_make_product_model_division', table_name='make_product_models')
    op.drop_index('ix_make_product_model_category_sub_category', table_name='make_product_models')
    op.drop_table('make_product_models')
    op.drop_index('ix_line_of_businesses_lob_name', table_name='line_of_businesses')
    op.drop_index('ix_line_of_businesses_division_name', table_name='line_of_businesses')
    op.drop_table('line_of_businesses')
    # ### end Alembic commands ###
