"""add make product model table and sync schemas

Revision ID: ee19748dd75b
Revises: acd7358a40d2
Create Date: 2026-09-18 22:17:57.855832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee19748dd75b'
down_revision: Union[str, Sequence[str], None] = 'acd7358a40d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('make_product_models',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=500), nullable=False),
    sa.Column('decal_model', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('sub_category', sa.String(length=255), nullable=True),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('jd_product_family', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_make_product_model_category', 'make_product_models', ['category'], unique=False)
    op.create_index('ix_make_product_model_category_id', 'make_product_models', ['category_id'], unique=False)
    op.create_index('ix_make_product_model_created_at', 'make_product_models', ['created_at'], unique=False)
    op.create_index('ix_make_product_model_division', 'make_product_models', ['division'], unique=False)
    op.create_index('ix_make_product_model_jd_product_family', 'make_product_models', ['jd_product_family'], unique=False)
    op.create_index('ix_make_product_model_make', 'make_product_models', ['make'], unique=False)
    op.create_index('ix_make_product_model_make_category', 'make_product_models', ['make', 'category'], unique=False)
    op.create_index('ix_make_product_model_make_division', 'make_product_models', ['make', 'division'], unique=False)
    op.create_index('ix_make_product_model_make_jd_product_family', 'make_product_models', ['make', 'jd_product_family'], unique=False)
    op.create_index('ix_make_product_model_make_model', 'make_product_models', ['make', 'model'], unique=False)
    op.create_index('ix_make_product_model_make_sub_category', 'make_product_models', ['make', 'sub_category'], unique=False)
    op.create_index('ix_make_product_model_model', 'make_product_models', ['model'], unique=False)
    op.create_index('ix_make_product_model_model_id', 'make_product_models', ['model_id'], unique=False)
    op.create_index('ix_make_product_model_product_id', 'make_product_models', ['product_id'], unique=False)
    op.create_index('ix_make_product_model_sub_category', 'make_product_models', ['sub_category'], unique=False)
    op.create_index('ix_make_product_model_sub_category_id', 'make_product_models', ['sub_category_id'], unique=False)
    op.create_index('ix_make_product_model_updated_at', 'make_product_models', ['updated_at'], unique=False)
    op.create_index(op.f('ix_make_product_models_category'), 'make_product_models', ['category'], unique=False)
    op.create_index(op.f('ix_make_product_models_category_id'), 'make_product_models', ['category_id'], unique=False)
    op.create_index(op.f('ix_make_product_models_make'), 'make_product_models', ['make'], unique=False)
    op.create_index(op.f('ix_make_product_models_model_id'), 'make_product_models', ['model_id'], unique=False)
    op.create_index(op.f('ix_make_product_models_product_id'), 'make_product_models', ['product_id'], unique=True)
    op.create_index(op.f('ix_make_product_models_sub_category'), 'make_product_models', ['sub_category'], unique=False)
    op.create_index(op.f('ix_make_product_models_sub_category_id'), 'make_product_models', ['sub_category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_make_product_models_sub_category_id'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_sub_category'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_product_id'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_model_id'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_make'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_category_id'), table_name='make_product_models')
    op.drop_index(op.f('ix_make_product_models_category'), table_name='make_product_models')
    op.drop_index('ix_make_product_model_updated_at', table_name='make_product_models')
    op.drop_index('ix_make_product_model_sub_category_id', table_name='make_product_models')
    op.drop_index('ix_make_product_model_sub_category', table_name='make_product_models')
    op.drop_index('ix_make_product_model_product_id', table_name='make_product_models')
    op.drop_index('ix_make_product_model_model_id', table_name='make_product_models')
    op.drop_index('ix_make_product_model_model', table_name='make_product_models')
    op.drop_index('ix_make_product_model_make_sub_category', table_name='make_product_models')
    op.drop_index('ix_make_product_model_make_model', table_name='make_product_models')
    op.drop_index('ix_make_product_model_make_jd_product_family', table_name='make_product_models')
    op.drop_index('ix_make_product_model_make_division', table_name='make_product_models')
    op.drop_index('ix_make_product_model_make_category', table_name='make_product_models')
    op.drop_index('ix_make_product_model_make', table_name='make_product_models')
    op.drop_index('ix_make_product_model_jd_product_family', table_name='make_product_models')
    op.drop_index('ix_make_product_model_division', table_name='make_product_models')
    op.drop_index('ix_make_product_model_created_at', table_name='make_product_models')
    op.drop_index('ix_make_product_model_category_id', table_name='make_product_models')
    op.drop_index('ix_make_product_model_category', table_name='make_product_models')
    op.drop_table('make_product_models')
    # ### end Alembic commands ###
